### ISSUE TITLE
Extra Filtering options and mass deleting

### ISSUE THREAD

**Issue by zealvix** [andresdelcampo/GameList_Editor#11]
Hi,

Would it be possible to consider adding more filtering/custom filtering options and allows mass deleting?

Trying to accomplish actions such as selecting all games < 0.5 rating (including actual game files) or deleting all games of a certain genre etc.

**Comment by andresdelcampo** [comment]
That sounds very doable... give me a week or two and you will have it :). Those filters / sorting are definitely missing. Deletion can be done quite fast currently by disabling the confirmation -and it is just arrow down, delete, arrow down, delete, etc. I left it out from the multiselection because it was quite dangerous and there was no way back... but I will then reconsider it as well.

**Comment by andresdelcampo** [comment]
Hi zealvix,

Good news! It is implemented now in the just released GameList Editor 2023.08!
Enjoy!
