### ISSUE TITLE
[Feature Request] Batocera Support

### ISSUE THREAD

**Issue by wesbeyrent** [andresdelcampo/GameList_Editor#12]
The tool does a great job loading the XML from my Batocera folder on the network, but I don’t get any images loaded. 

I’d also love to be able to flag games as kid friendly, like you can do in the Batocera menu.

**Comment by andresdelcampo** [comment]
Hi webeyrent, thanks for your feedback. 

I am sorry to hear about the image issues. I heard about those a couple of times in the past. One of them was solved in code -but I am assuming you are running a recent enough version- and the other one was diagnosed in https://github.com/andresdelcampo/GameList_Editor/discussions/7
I will revisit it and see if I can override the absolute path assuming that is the case.

Sure, adding the Kid friendly support should not be a big effort, count on it. Probably in the next few days.

**Comment by andresdelcampo** [comment]
Just to be sure, could you please share a fragment of the failing gamelist.xml file, in particular the tag with the image (that does not show) of a game?

**Comment by wesbeyrent** [comment]
No problem! Here’s my entire Dreamcast gamelist file. This is just one
example from the whole library. Let me know if there’s anything else you
need, and thanks for the quick reply and support!

**Comment by andresdelcampo** [comment]
Hmm... that's worrying... they are not even absolute paths! That should have worked. I will try to setup a new Batocera setup and see if it reproes. Just please confirm you are running 2022.04 or later as that version fixed a similar issue and I could be chasing ghosts then. But yes, it sounds quite an important issue. If repro I should have a fix in the next few days.

**Comment by andresdelcampo** [comment]
I have installed a new Batocera on Pi4, and I can connect via wireless from my PC without issues -shows images, videos, etc. I also tried including the Crazy taxi 2 entry as a c64 game, just copying files from Fix it felix and renaming them... and it also shows fine. 

Is the issue something that was working before and suddenly stopped working? It sounded like it was never working but that makes it even weirder. I wonder if the problem is not the gamelist but the images format/content instead?

Is this about Batocera on x86? I am trying to install it as well to verify.

**Comment by andresdelcampo** [comment]
On the other hand... good news!, GameList Editor 2023.09 now supports kidgame tag (Kid Friendly).

**Comment by wesbeyrent** [comment]
Absolutely amazing! Thank you so much! The kidgame tag works perfectly.  

Interestingly, all my systems load the images now, except for Dreamcast.  However, whenever I switch to the video tab for any game on any system, the app crashes.  Maybe I need a specific .net framework or something?

Also, yes, I'm running Batocera on an x86 64bit machine, if that helps.

Thanks!

**Comment by andresdelcampo** [comment]
:D, well, there was no change at all on how images are loaded... so I cannot explain why it would work or stop working... though I still suspect it is something with the image format. For the fun of it, replace one temporarily with the image of a game of another folder that works -but renamed and copied in the location of the Dreamcast game (back up the original image of course). If it loads, it is the image format. 

But on videos, maybe installing this might fix it: https://support.microsoft.com/en-us/windows/get-windows-media-player-81718e0d-cfce-25b1-aee3-94596b658287
It is supposed to be in Windows, but not in all versions. Let me know if that worked, maybe I can somehow prevent that crash and give proper instructions instead.

**Comment by wesbeyrent** [comment]
:facepalm:

My whole Dreamcast/images folder was messed up. I rescraped the folder from
within Batocera and all is well.

I have Windows 11 with Windows Media Player, but still get the crashes.

Thanks!

**Comment by andresdelcampo** [comment]
Great to hear -that is 2 out of 3 problems nailed down. 

About the crashes... try https://support.microsoft.com/en-us/topic/media-feature-pack-list-for-windows-n-editions-c1c6fffa-d052-8338-7a79-a4bb980a700a and see if this helps -let me know if it does and I will add it to the Readme

**Comment by wesbeyrent** [comment]
Thanks! I tried that support link, but the "Media Feature Pack" it mentions
doesn't show up in the list of optional features.  Per the support
article's instructions:

   - *On Windows 11 N: *Select the *Start *button, then select *Settings >
   Apps > Optional features*. Select *View features* next to *Add an
   optional feature*, and then select the *Media Feature Pack *in the list
   of available optional features.

I'm running 22H2, OS Build 22621.2134, Windows Media Player version
11.2305.4.0.

**Comment by andresdelcampo** [comment]
In that case it is not a Windows N problem. That said, I did try once a clean Windows install with a VM and the videos played fine. So one thing to check is if you can actually play the videos with Windows Media Player -the same videos that crash GameList Editor. If they cannot open due to a codec issue, then the solution would be to install the relevant codec. I would recommend then to install https://codecguide.com/download_kl.htm
Let me know how it goes!

**Comment by wesbeyrent** [comment]
Hi Andres,

I'm stumped.  The videos play fine in Media Player when I open them from
windows explorer, but still crash when trying to play in the app.  I
installed the codec pack too, but same thing.  I also ran the app as
administrator, just in case.  Still crashes.

Maybe I'm an extreme edge case.  You've done so much already, don't beat
your head on a wall for this one!  If I figure something out, I'll let you
know!

Best,
Wes

**Comment by andresdelcampo** [comment]
Hi Wes, 

That's extremely weird, but you may not be the only one. So worth a shot.

Two things come to my mind at this point. Just to rule everything out, consider running it without the antivirus -Avast was crashing it for me from time to time, but it was usually opening roms folders, not videos... but who knows-. It was because of the file/folder crawling when reading all systems and roms that sounded suspicious to the antivirus. That said, running as admin should not be necessary unless your rom folders are restricted somehow. 

Another one is if you get any meaningful info out of the crash that could help troubleshoot it. As it is probably not enough, here is a special version of GameList Editor that should output the whole exception message as a pop up. Please send the text back to me :). You can find that version in https://mega.nz/file/bmAHjYZD#8zjfnK8-lN0cgXVIMlB3KSEURuxss1wVbs-fgelI3uA 

It is very weird to be able to play the videos outside and not in the app, because the component used is a Windows ActiveX (Windows Media Player) directly...  Surely if the videos played fine outside, it is not a codec issue. Now, it also depends a lot which app is playing the videos -we are talking Windows Media Player potentially the legacy version rather than the newest. So maybe that one behaves differently. 

Good hunting!
Andrés

**Comment by andresdelcampo** [comment]
Awesome news! 

I suspect it may have to be with VLC installing Windows Media Player legacy, that may have fixed it. 

Beyond that, I guess it did not crash in the place I thought it did -when starting a video- but somewhere else initializing the video player. But, that does not matter much now :). 

Enjoy!!
