### ISSUE TITLE
Possible systems subfolders support?

### ISSUE THREAD

**Issue by Oberworld** [andresdelcampo/GameList_Editor#20]
As the title of the post indicates, would it be possible to add support for subfolders?
Many of my systems contain a subfolder called "homebrew". 
Homebrew games are often difficult to scrape and Gamelist editor is very useful for editing the metadata.
The subfolder is shown in the main menu but I can't access it.
All the metadata for the games in "homebrew" subfolder is inside the main gamelist.xml, for example inside roms>nes>gamelist.xml.
Thanks in advance, great job with the program.
Regards.

**Comment by andresdelcampo** [comment]
Hmm... having the metadata in the main folder xml makes things a lot easier. So it looks like just patching the rom search to look in subdirectories as well -assuming it is not doing part of that already... I will have a look in the next few days / weekend. Maybe I can give you good news :).

**Comment by Oberworld** [comment]
Thank you very much. I'll stay tuned.

Muchas gracias por tomarte la molestia andrés. Estaré atento.

**Comment by andresdelcampo** [comment]
Hi! Hola! 
I am not sure what the problem is... 
* I set a typical system structure 
* I added a homebrew subfolder inside one of the systems
* I altered gamelist.xml to point to the path of the subfolder...
and all works normally out of the box :)

![image](https://github.com/user-attachments/assets/866292ed-979f-425e-abaa-5faa7e4adc48)

Maybe it is just making sure that the path tag of your gamelist games points to where they really are?
![image](https://github.com/user-attachments/assets/1a0fced4-a23c-4b9f-9cb6-0cbfdb30a125)

Else I do not understand what you are missing in the tool? It seems to handle fine the games that are in subfolders inside that system -they show as part of the system, not as a separate system or folder. That part is unlikely to change. But there are always things that can make the handling easier like adding a "Same path" filter -that is not there yet.

**Comment by Oberworld** [comment]
I'm sorry, GameList Editor is working fine, I was confused.
I have my subfolder named "#Homebrew" and it's in my main gamelist.xml as if it were a game so I can put an image and logo on it.
```

	<folder>
		<path>./#Homebrew</path>
		<name>#Homebrew</name>
		<image>./images/#Homebrew-image.png</image>
		<marquee>./images/#Homebrew-marquee.png</marquee>
	</folder>
```

In GameList Editor it does show the first one in the list by its name, and I tried to click to open it, without realizing that what it shows is the folder as a game.

I hadn't noticed that the games were mixed with those in the main system folder.

Anyway, it would be nice if the subfolders were shown on top of the main gamelist and could be clicked so as not to mix all the games in the main system folder.

Sorry so much to have wasted your time, thanks for the help.
Regards.

**Comment by andresdelcampo** [comment]
No problem. The AI fooled me believing there is indeed a folder tag -to later say there is not, or at least not standardized. While a file system-like navigation would be hard to implement, I can think of at least the "Same folder" filter so that after clicking one of the games and filtering, you only see the ones in the same folder. That should not be hard to implement on my end and should mostly address the need to separate the homebrew or in general any subfolder -or the root- from the rest within the same system... if you think it is valuable? What do you think?

**Comment by Oberworld** [comment]
I think having the option to separate the games by "same folder" as you say, can be useful.
At least in my case, many systems even have two subfolders, for example, in zxspectrum, amstradcpc and amiga I have the subfolders homebrew and conversational adventures.
I think it would be great to be able to separate the games, but I'm not a programmer and I don't know if it's worth the effort. If it's not a lot of work, it would be great to have that option.

If you decide to do so, it would be nice to put separators (lines) in the game list to separate games that are in different folders.

Example image:

![Sin título 1](https://github.com/user-attachments/assets/3547ac3d-c15f-4ebc-ae92-891f7fac8f01)

**Comment by andresdelcampo** [comment]
Well, the full idea you are proposing would not be that fast... what I was proposing does not disrupt the current flow of the application -it still keeps a single folder content per system, yet it still gives you the chance to see the system with a different filter. Same way we can filter for "Favorites" or by Genre to see only those games, we have filters already for same number of players, for example. If you choose a game with 4 players, then choose the filter Same number of players, then the list only shows those that are for 4 players. I was thinking that I can relatively easily add a new filter "Misma carpeta"/"Same folder" to filter those games that are exactly in the same folder -not subfolders or parent folders... The only drawback is that you start with all and have to locate first a game from that folder to filter the rest. What do you think? Would that help? 

![image](https://github.com/user-attachments/assets/d0f370e5-94f5-4b1f-b169-0c31a1613ce9)

**Comment by andresdelcampo** [comment]
Have a look... it's released :)

**Comment by Oberworld** [comment]
Wow! That was fast. I'll take a look at it as soon as I can.
Thank you so much.

**Comment by Oberworld** [comment]
OK, my mistake again, I haven't scraped that system yet because I was doing a "rom cleanup" before scraping everything.
Therefore in the gamelist.xml only the games I've tried are shown, even if they are not scraped.
Gamelist editor is working great.
Thanks a lot for everything, you're doing a great job.

**Comment by andresdelcampo** [comment]
Awesome! I know it is not a full solution, but if more people show interest I may revisit this with a better solution. In the meantime the workaround should solve most needs :).
