### ISSUE TITLE
Application Error - Class not registered

### ISSUE THREAD

**Issue by macariocarneiro** [andresdelcampo/GameList_Editor#8]
App version: GameList Editor 2022.04

System: Windows 10 Pro 21H2 build 19044.1889

Error: Application Error - Exception EOleSysError in module GameListEditor.exe at 00155159. Class not registered

How to reproduce the error:
- unzip files to a folder
- execute GameListEditor.exe from File Explorer

**Comment by andresdelcampo** [comment]
Thanks for reporting the issue -and for the details. I am quite surprised about it. I will investigate during the next 3-5 days and let you know if I can find out what may be missing. My first suspicion is lack of video related support in Windows. If you cannot open game videos directly from file explorer either, that might be the issue. Installing a codec like K-Lite might do it ( https://codecguide.com/download_kl.htm ) as GameList Editor relies on Windows for video playing. Let me know if that was the issue. I will have a look the next few days otherwise.

**Comment by macariocarneiro** [comment]
Tested in another PC and is working fine

Edição	Windows 11 Home Single Language
Versão	21H2
Instalado em	‎20/‎04/‎2022
Compilação do SO	22000.978
Experiência	Pacote de Experiência de Recursos do Windows 1000.22000.978.0

**Comment by andresdelcampo** [comment]
I am researching a bit, it could be that one of the ActiveX components got unregistered. Curiously enough, many blame that error on Windows directly rather than on any app. I started developing it in Win 10 Pro too, so the Windows version should not be a problem. 
Either way, did you get a Class ID with the error message (a long GUID -many letters and numbers just like for example {34792e53-d0f5-4277-83b6-55daf8500018}. That would narrow down the class component that is not found.

**Comment by andresdelcampo** [comment]
Hmm... I do not see any problem in a clean installation of Windows. It even plays videos out of the box. I suspect VideoLan or something else altered / unregistered some out of the box classes. So I start to think that the people online were right and this was not an app issue but an OS configuration issue after all. Still, if you find a class ID, it might point to what component is wrong with your set up, but I do not see an application issue here at the moment.
![image](https://user-images.githubusercontent.com/33843515/193452416-f632978c-f9e3-4384-b73f-ee85b9504064.png)

**Comment by andresdelcampo** [comment]
It also occurred to me that the issue might be caused by having the "N" version of Windows (Windows 10 Pro N), which removes the Windows Media components. That would definitely fail. In that case, you would want to install the Media Feature Pack from https://support.microsoft.com/en-us/topic/media-feature-pack-list-for-windows-n-editions-c1c6fffa-d052-8338-7a79-a4bb980a700a

**Comment by andresdelcampo** [comment]
Refer to https://github.com/andresdelcampo/GameList_Editor/issues/18#issuecomment-1902772711 for a confirmed solution -in case this wasn't solved back then.
