### ISSUE TITLE
[Feature Request] Implement bulk actions on multiple entries

### ISSUE THREAD

**Issue by Clearmist** [andresdelcampo/GameList_Editor#9]
It is possible to select multiple entries within the game list, but there are no available bulk actions.
![image](https://github.com/andresdelcampo/GameList_Editor/assets/4317724/c8439ffe-4234-4223-b909-785b677333cb)

## Requested feature

Allow the user to make bulk changes when selecting multiple files. This may include:

1. Setting each to "hidden".
2. Setting each to "favorite".
3. Updating the region or genre.
4. Remove the entries from the gamelist.xml file.
5. Delete picture or video.

**Comment by andresdelcampo** [comment]
Thanks Clearmist, that is a great idea! Let me see what I can do...

**Comment by andresdelcampo** [comment]
Note also that the first two are already there -just a bit hidden:

![image](https://github.com/andresdelcampo/GameList_Editor/assets/33843515/d84595f8-3fea-41ff-996b-c8326d024ae0)

How much interest do you have in the other 3? This is what I can see: 
* Updating regions or genres -or even other fields like Developer- is a valid case that would save some time as it is both altering the field and saving each game. I will consider that one. That could make even setting Favorites or Hidden a bit more user friendly as it would have a "Save Changes for selected games" button and it hopefully would not refresh the list as it does today.
* About removal from gamelist.xml, wouldn't it be better then to mark them as hidden if you want to keep the media files? -so that you can easily reactivate them if you want to. I do not see why you would want to keep the list not synced with the files in the folder, and having a second Delete button could add confusion. I added functionality last year so that it will not delete videos or images if they are shared with other games in the list, so Deleting a game with its files should be ok in most cases.
* I have mixed feelings with the mass deletion. You can do it very quickly with cursor keys traversing the list, and clicking on Delete Picture or Delete Video -after you have seen it game by game. Those do not require you to click Save Changes.  Like Delete Game, there is no undo in those options and you have to manually set it back, which is far more time consuming if the deletion was not intended. I have personally been using the Delete options a lot when curating my own lists, and I did find them fast to use. Note also that if you are Deleting the whole game, you have an option that you can enable to remove the confirmation to delete the game if you want fast deletes -that does not apply to video or image that do not have one.
 
![image](https://github.com/andresdelcampo/GameList_Editor/assets/33843515/71d2a9bb-a58d-43d6-8fd1-841221b1a1b1)

Let me know what you think!

**Comment by Clearmist** [comment]
I definitely defer to you as the developer. The ScreenScraper software called Skraper includes ways of excluding games rather than hiding them so my suggestion was to help the users who prefer exclusion. You're right that hiding them is probably the better choice.

Regarding deletion of media: I was brainstorming other bulk actions and thought of that one. I probably wouldn't use it, but my thought process was: if there is an action that can be performed on a single record then that action should have a bulk version, too. :) I hope that makes sense.

**Comment by andresdelcampo** [comment]
I finally decided to go ahead with it... and here it is! [GameList Editor 2023.07 ](https://github.com/andresdelcampo/GameList_Editor/releases/tag/2023.07) includes batch editing. That effectively addresses the first 3 points you requested. So now you can also set favorite or hidden using batch editing in the fields themselves, together with the rest of the fields that were not possible to batch update before.

I have left the deletions or exclusions out for now -I can easily add them if required later, but they can be VERY dangerous-.  If more people request them, I will be happy to add them too.
